# --- General ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 0
setw -g pane-base-index 0
set -g renumber-windows on
set -g history-limit 10000

# --- Enable undercurls ---
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# --- Splits ---
bind | split-window -h -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# --- Pane navigation ---
set -g repeat-time 5
set -s escape-time 5
bind h select-pane -L
bind C-h select-pane -L
bind j select-pane -D
bind C-j select-pane -D
bind k select-pane -U
bind C-k select-pane -U
bind l select-pane -R
bind C-l select-pane -R

# --- Reload config ---
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# --- TPM (Tmux Plugin Manager) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# --- Dracula theme ---
set -g @dracula-show-powerline true
set -g @dracula-plugins "git time"
set -g @dracula-show-left-icon session
set -g @dracula-git-colors "light_purple dark_gray"
set -g @dracula-show-empty-plugins false

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
